CardPatient/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CardPatient.Models;
using CardPatient.Context;


namespace CardPatient.Controllers
{
    [Authorize]
    public class BaseController : Controller
    {
        
        CardContext dbCard;
        HistoryContext dbHistory;
        private string lastIIN;
        // GET: Base
        public BaseController()
        {
            dbCard = new CardContext();
            dbHistory = new HistoryContext();
        }
    

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Card card)
        {
            Card cardPatient = null;
            if (ModelState.IsValid)
            {
                dbCard.Cards.Add(card);
                lastIIN = card.IIN;
                dbCard.SaveChanges();
                cardPatient = card;
            }
            return RedirectToAction("HistoryVisit");
        }
        public ActionResult HistoryVisit()
        {
            History history = new History();
            history.FullNameDoctor = User.Identity.Name;
            history.DateVisit = DateTime.Now;
            return View(history);
        }
        private int GetLastIdList(List<Card>db) 
        {
            return db.LastOrDefault().id;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult HistoryVisit(History history)
        {
            List<Card> obj;
            using (CardContext db = new CardContext())
            {
                obj = db.Cards.ToList();
            }
            history.idPatient = GetLastIdList(obj);
            History historyPatient = null;
            if (ModelState.IsValid)
            {
                dbHistory.Histories.Add(history);
                dbHistory.SaveChanges();
                historyPatient = history;
            }
            return View("DoctorsPatient");
        }
        private IOrderedEnumerable<Card> SortPatientsName(List<Card> cards)
        {
            return from u in cards
                   orderby u.FullName
                   select u; ;
        }
        private List<Card> GetPatients()
        {
            List<Card> cards = new List<Card>();
            using(CardContext db = new CardContext())
            {
                var temp = SortPatientsName(db.Cards.ToList());
                foreach(var item in temp)
                {
                    cards.Add(item);
                }
            }
            return cards;
        }
        public ActionResult Patients()
        {
            return View(GetPatients());
        }
    }
}

CardPatient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Добро пожаловать " + User.Identity.Name.ToString(), "Index", "Home")</li>

                    }
                    else
                    {
                        <li>@Html.ActionLink("Войти/Регистрация", "Base", "Login")</li>

                    }
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("Информация", "About", "Home")</li>
                    <li>@Html.ActionLink("Связаться", "Contact", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Выйти ", "Logoff", "Account")</li>

                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - мое приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>